"""Change verification_code to Integer

Revision ID: efca9b823ba4
Revises: 790bbdc8ce27
Create Date: 2025-01-07 16:42:10.827930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'efca9b823ba4'
down_revision: Union[str, None] = '790bbdc8ce27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verification_code',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verification_code',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###
